name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm ci --ignore-scripts
      - run: |
          npm run all
        env:
          access-token: ${{ secrets.WORKPLACE_ACCESS_TOKEN }}
          thread-key: ${{ secrets.WORKPLACE_THREAD_KEY }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          access-token: ${{ secrets.WORKPLACE_ACCESS_TOKEN }}
          thread-key: ${{ secrets.WORKPLACE_THREAD_KEY }}
          text: 'Successful test!'
